"""Add bank statement uploads table

Revision ID: 05c8432db50b
Revises: dff57d99aad6
Create Date: 2025-01-01 19:00:31.281866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05c8432db50b'
down_revision = 'dff57d99aad6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alert_configuration', schema=None) as batch_op:
        batch_op.drop_constraint('alert_configuration_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('alert_history', schema=None) as batch_op:
        batch_op.drop_constraint('alert_history_user_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('alert_history_alert_config_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'alert_configuration', ['alert_config_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('bank_statement_upload', schema=None) as batch_op:
        batch_op.drop_constraint('bank_statement_upload_user_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('bank_statement_upload_account_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'account', ['account_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('company_settings', schema=None) as batch_op:
        batch_op.drop_constraint('company_settings_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('financial_goal', schema=None) as batch_op:
        batch_op.drop_constraint('financial_goal_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('financial_recommendation', schema=None) as batch_op:
        batch_op.drop_constraint('financial_recommendation_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('historical_data', schema=None) as batch_op:
        batch_op.drop_constraint('historical_data_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('recommendation_metrics', schema=None) as batch_op:
        batch_op.drop_constraint('recommendation_metrics_recommendation_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'financial_recommendation', ['recommendation_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('risk_assessment', schema=None) as batch_op:
        batch_op.drop_constraint('risk_assessment_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('risk_indicator', schema=None) as batch_op:
        batch_op.drop_constraint('risk_indicator_assessment_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'risk_assessment', ['assessment_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_constraint('transaction_file_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('transaction_user_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('transaction_account_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'account', ['account_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'uploaded_file', ['file_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('uploaded_file', schema=None) as batch_op:
        batch_op.drop_constraint('uploaded_file_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploaded_file', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('uploaded_file_user_id_fkey', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('transaction_account_id_fkey', 'account', ['account_id'], ['id'])
        batch_op.create_foreign_key('transaction_user_id_fkey', 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key('transaction_file_id_fkey', 'uploaded_file', ['file_id'], ['id'])

    with op.batch_alter_table('risk_indicator', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('risk_indicator_assessment_id_fkey', 'risk_assessment', ['assessment_id'], ['id'])

    with op.batch_alter_table('risk_assessment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('risk_assessment_user_id_fkey', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('recommendation_metrics', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('recommendation_metrics_recommendation_id_fkey', 'financial_recommendation', ['recommendation_id'], ['id'])

    with op.batch_alter_table('historical_data', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('historical_data_user_id_fkey', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('financial_recommendation', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('financial_recommendation_user_id_fkey', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('financial_goal', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('financial_goal_user_id_fkey', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('company_settings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('company_settings_user_id_fkey', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('bank_statement_upload', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('bank_statement_upload_account_id_fkey', 'account', ['account_id'], ['id'])
        batch_op.create_foreign_key('bank_statement_upload_user_id_fkey', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('alert_history', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('alert_history_alert_config_id_fkey', 'alert_configuration', ['alert_config_id'], ['id'])
        batch_op.create_foreign_key('alert_history_user_id_fkey', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('alert_configuration', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('alert_configuration_user_id_fkey', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###
