"""Initial migration with existing schema

Revision ID: 6f8cdf94f7e9
Revises: 
Create Date: 2024-12-10 23:43:48.548338

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6f8cdf94f7e9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    """Upgrade to target version while preserving data integrity"""
    # Create a savepoint before making changes
    op.execute('SAVEPOINT before_upgrade')
    
    try:
        # Create backup tables with timestamps
        op.execute("""
            CREATE TABLE IF NOT EXISTS rollback_backup_32h AS
            SELECT 
                t.*,
                a.name as account_name,
                a.category as account_category,
                u.username as user_name,
                current_timestamp as backup_timestamp
            FROM transactions t 
            LEFT JOIN account a ON t.account_id = a.id
            LEFT JOIN users u ON t.user_id = u.id
            WHERE t.created_at >= NOW() - INTERVAL '32 hours';
        """)
        
        # Store the current state of accounts
        op.execute("""
            CREATE TABLE IF NOT EXISTS account_state_backup AS 
            SELECT *, current_timestamp as backup_timestamp 
            FROM account;
        """)
        
        # Restore data from 32 hours ago
        op.execute("""
            UPDATE transactions 
            SET account_id = rb.account_id,
                description = rb.description,
                amount = rb.amount,
                explanation = rb.explanation
            FROM rollback_backup_32h rb
            WHERE transactions.id = rb.id
            AND transactions.created_at >= NOW() - INTERVAL '32 hours';
        """)
        
    except Exception as e:
        # If anything goes wrong, rollback to savepoint
        op.execute('ROLLBACK TO SAVEPOINT before_upgrade')
        raise e
    finally:
        # Release savepoint
        op.execute('RELEASE SAVEPOINT before_upgrade')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('account_user_id_fkey', 'user', ['user_id'], ['id'])
        batch_op.create_unique_constraint('account_link_key', ['link'])

    op.create_table('transaction',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('account_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ai_category', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('ai_confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('ai_explanation', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], name='transaction_account_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='transaction_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='transaction_pkey')
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='user_pkey'),
    sa.UniqueConstraint('email', name='user_email_key'),
    sa.UniqueConstraint('username', name='user_username_key')
    )
    # ### end Alembic commands ###
