"""Add bank statement uploads table

Revision ID: d21d2362be68
Revises: 21ac658e2b56
Create Date: 2025-01-02 01:52:13.044286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd21d2362be68'
down_revision = '21ac658e2b56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('ai_category')
        batch_op.drop_column('ai_confidence')
        batch_op.drop_column('ai_explanation')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('user_reset_token_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint('user_reset_token_key', ['reset_token'])

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_explanation', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('ai_confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('ai_category', sa.VARCHAR(length=50), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
